import mongoose from "mongoose"

const productSchema = new mongoose.Schema({
    name: { type: String, required: true },
    code: { type: String, required: true, unique: true },
    prefijo: { type: String },
    tipo: { type: String },
    espesor: { type: String },
    detalle: { type: String },
    terminacion: { type: String },
    color: { type: String },
    colorMode: { type: String, default: 'especifico' },
    selectedColors: [{ type: String }],
    tipoTerminacion: { type: String },
    variantes: [{
        tipoProducto: String,
        tipoTerminacion: String,
        terminacion: String,
        precioGeneral: Number,
        precioGrupoI: Number,
        precioGrupoII: Number,
        precioGrupoIII: Number,
    }],
    medida: { type: String },
    nomenclaturaMedida: { type: String },
    m2: { type: Number },
    grupo: { type: String },
    image: { type: String },
    catalogo: { type: String },
    fichaTecnica: { type: String },
    archivos: [{
        titulo: String,
        url: String,
    }],
    espesoresMedidas: [{
        espesor: String,
        medida: String,
        nomenclaturaMedida: String,
        m2: Number,
        variantes: [{
            tipoProducto: String,
            tipoTerminacion: String,
            terminacion: String,
            precioGeneral: Number,
            precioGrupoI: Number,
            precioGrupoII: Number,
            precioGrupoIII: Number,
        }],
    }],
    precio: { type: Number },
    precioGeneral: { type: Number },
    unidadPrecio: { type: String, default: 'hoja' },
    admiteDescuentos: { type: Boolean, default: true },
    comentario: { type: String },
    stock: { type: Number, default: 0 },
    colors: [{ type: String }],
    dimensions: { type: String },
    thicknesses: [{ type: String }],
    pricePerM2: { type: Number, default: null },
    precioGrupoI: { type: Number },
    precioGrupoII: { type: Number },
    precioGrupoIII: { type: Number },
    tieneAgregado: { type: Boolean, default: false },
    agregadoNombre: { type: String, default: '' },
    agregadoPrecio: { type: Number, default: null },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
})

export default mongoose.model("Product", productSchema)
